name: CI - Tests Unitarios Jest

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test-unitarios:
    name: Ejecutar suite Jest
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests unitarios
        run: npm test